### ISSUE TITLE
INSERT to db json2mysql example

### ISSUE THREAD

**Issue by vibrion121** [caitken-com/node-red-contrib-json2mysql#2]
Im trying to insert into mariadb trough json2mysql but im failling miserably. I can do simple select and joins using examples. Do you have an INSERT example? Thanks!!

**Comment by caitken-com** [comment]
Hi @vibrion121,
sorry for the late response - my email client died!

Here's some better documentation: https://github.com/caitken-com/SimpleSqlBuilder
json2mysql is a wrapper for my SimpleSqlBuilder project.

**Comment by caitken-com** [comment]
```json
{
    "insert": {
         "table": "users",
         "columns": {
              "first_name": "?",
              "last_name": "?",
              "age": "?"
         }
     },
     "params": [
        "John",
        "Doe",
        30
     ],
     "return": "count"
}
```

**Comment by yNosGR** [comment]
Sorry if I'm being dense or using this beyond it's intent here, but I am having a problem filling in the params for an insert. Can I get a little guidance?
```
{
    "insert": {
        "table": "site_log",
        "columns": {
            "uploaded": false,
            "headwater": "?",
            "tailwater": "?",
            "nethead": "?",
            "plantflowcfs": "unknown",
            "gen1_wickets": "?",
            "gen1_flow": "unknown",
            "gen1_kw": "?",
            "bearing1": "?",
            "bearing2": "?",
            "totalkw": "?",
            "username": "nr-logger"
        }
    },
    "params": [
        "msg.payload.site3.hydrology.headwater_sensor.computed",
        "msg.payload.site3.hydrology.tailwater_sensor.computed",
        17,
        "msg.payload.site3.gen1.wickets.computed",
        "msg.payload.site3.gen1.kw.value",
        "msg.payload.site3.gen1.bearing.upper.value",
        "msg.payload.site3.gen1.bearing.lower.value",
        "msg.payload.site3.gen1.kw.value"
    ],
    "return": "count"
}

**Comment by caitken-com** [comment]
Hi @yNosGR,
What you’ve done looks correct, except you’ve put quotes around your variables making them static literal values/strings.
Eg:
`"msg.payload.site3.gen1.wickets.computed",`
The fix:
`msg.payload.site3.gen1.wickets.computed,`

**Comment by yNosGR** [comment]
Hmm, I'll try it again, maybe it has a typo I missed.

**Comment by yNosGR** [comment]
No, we are still getting ` [warn] [json2mysql:insertInto_test] SyntaxError: Unexpected token m in JSON at position 470` which ends up being the first line we try to call `msg.payload.site3.hydrology.headwater_sensor.computed`.  With No quotes, it shows errors (the red blocks/underlines) in the nodered linter/editor. Is there some escaping that I'm, doing wrong? I'm running v3.1.1
![Screenshot 2023-12-10 18 25 15](https://github.com/caitken-com/node-red-contrib-json2mysql/assets/16291100/0efa05b3-72cb-401b-b8b0-a2ed0ffab14b)

**Comment by caitken-com** [comment]
What kind of node are you writing your json in that screen-shot? It appears it can't read the variable `msg.payload.site3.gen1.wickets.computed`. I think the issue is what node kind you're trying to write your json in. I'd personally use a **function** node.
![Screenshot 2023-12-11 at 12 20 18 pm](https://github.com/caitken-com/node-red-contrib-json2mysql/assets/40314295/443bf8ae-8796-42ff-9d77-5f924608a5b9)

**Comment by yNosGR** [comment]
The endpoints I grabbed are being used by other functions..
![Screenshot 2023-12-10 20 43 34](https://github.com/caitken-com/node-red-contrib-json2mysql/assets/16291100/1603bd33-6ad9-4075-8708-1f4fd6fd7877)

**Comment by caitken-com** [comment]
In between your json node and your insertinto node, add the function node as per my example above.
`http-node -> json-node -> *function-node* -> json2sql-node`

Everything else can stay as you have. You just need to add that extra function node _before_ json2sql-node.

**Comment by yNosGR** [comment]
I've inserted the function, even made it re-map things down to make it a little easier to copy it over to the other sites. We still get errors that seem to either be the json interpreter complaining, or maybe the json linter complaining about it not being proper json? 
![Screenshot 2023-12-10 23 12 00](https://github.com/caitken-com/node-red-contrib-json2mysql/assets/16291100/b7115b54-4d08-492c-b44a-ecf505e141cd)

**Comment by caitken-com** [comment]
Hi @yNosGR.
your screenshot still suggests that is _not_ a function node. Are you using the template field within the json2sql node?? Because that can not be used to grab values from the previous node(s), it's a static _json string_.

If you want to use the json template field. Do this:
### json2sql node's template field:
```json
{
    "insert": {
        "table": "site_log",
        "columns": {
            "uploaded": false,
            "headwater": "?",
            "tailwater": "?",
            "nethead": "?",
            "plantflowcfs": "unknown",
            "gen1_wickets": "?",
            "gen1_flow": "unknown",
            "gen1_kw": "?",
            "bearing1": "?",
            "bearing2": "?",
            "totalkw": "?",
            "username": "nr-logger"
        }
    },
    "return": "count"
 }
 ```
###  testFunction node:
```js
let payload = {
    "params": [
        msg.payload.site3.hydrology.headwater_sensor.computed,
        msg.payload.site3.hydrology.tailwater_sensor.computed,
        17,
        msg.payload.site3.gen1.wickets.computed,
        msg.payload.site3.gen1.kw.value,
        msg.payload.site3.gen1.bearing.upper.value,
        msg.payload.site3.gen1.bearing.lower.value,
        msg.payload.site3.gen1.kw.value
    ]
};

msg.payload = payload;
return msg;
```

This will update (inject) the static json template with the dynamic params of your flow.

**Comment by yNosGR** [comment]
Sweet, it works. Thanks for the assist here, It's been driving me nuts for a few days. 
I ended up moving the params section out of the json2mysql node and into the function section as it shows in your latest reply.
## json2Mysqlfunction Node
```var siteName = msg.payload.longcastle.siteName;
let payload = {
    "params": [
        parseFloat(msg.payload[siteName].hydrology["headwater_sensor"].computed),
        parseFloat(msg.payload[siteName].hydrology["tailwater_sensor"].computed),
        0,
        parseInt(((msg.payload[siteName].gen1["wicket_closed_cts"].value-40)*((1-100)/(3280-32768)))+1),
        parseInt(msg.payload[siteName].gen1.kw.value),
        parseInt(msg.payload[siteName].gen1.bearing.upper_temp.value),
        parseInt(msg.payload[siteName].gen1.bearing.lower_temp.value),
        parseInt(msg.payload[siteName].gen1.kw.value),
        "nrLogger"
    ]
};

msg.payload = payload;
return msg;
```
# json2Mysql Node 
```
{
    "insert": {
        "table": "s3_site_log",
        "columns": {
            "uploaded": false,
            "headwater": "?",
            "tailwater": "?",
            "nethead": "?",
            "plantflowcfs": 0,
            "gen1_wickets": "?",
            "gen1_flow": 0,
            "gen1_kw": "?",
            "bearing1": "?",
            "bearing2": "?",
            "total_kw": "?",
            "username": "?"
        }
    },
    "return": "count"
}
```

**Comment by caitken-com** [comment]
Nice work.
